# This compose file is compatible with Compose itself, it might need some
# adjustments to run properly with stack.

version: '3'

services:

  synapse:
    image: docker.io/chatopia/synapse:latest
    # Since synapse does not retry to connect to the database, restart upon
    # failure
    restart: unless-stopped
    # See the readme for a full documentation of the environment settings
    environment:
      # There are many other supported environment variables that are not
      # used here. See https://hub.docker.com/r/matrixdotorg/synapse/
      - SYNAPSE_SERVER_NAME=chat.sneakyfrog.com
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_ENABLE_REGISTRATION=yes
      - SYNAPSE_LOG_LEVEL=INFO
      # TODO Change this and move it out of the config file
      - POSTGRES_PASSWORD=*EW>6,?3f3TLP2ikPdZs
      - SYNAPSE_ACME=1
    depends_on:
      - db
      - bridge
    # In order to expose Synapse, remove one of the following, you might for
    # instance expose the TLS port directly:
    ports:
      - "8448:8448/tcp"
      - "80:8009/tcp" # Necessary for automatic certificate requests

  db:
    image: docker.io/postgres:10-alpine
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=*EW>6,?3f3TLP2ikPdZs

  irc:
    image: inspircd/inspircd-docker:latest
    ports:
      - "6667:6667/tcp"

  bridge:
    image: chatopia/matrix-appservice-irc:latest
    depends_on:
      - irc
    # We may not need this open to the host
    ports:
      - "9999:9999/tcp"
    entrypoint:
      - "/app/docker/start.sh"
      - "-c"
      - "config/server-config.yaml"
      - "-f"
      - "config/appservice-registration-irc.yaml"
      - "-p"
      - "9999"
