# This compose file is compatible with Compose itself, it might need some
# adjustments to run properly with stack.

version: '3'

services:

  synapse:
    image: docker.io/chatopia/synapse:latest
    # Since synapse does not retry to connect to the database, restart upon
    # failure
    restart: unless-stopped
    # See the readme for a full documentation of the environment settings
    environment:
      - SYNAPSE_SERVER_NAME=chat.sneakyfrog.com
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_ENABLE_REGISTRATION=yes
      - SYNAPSE_LOG_LEVEL=INFO
      # TODO Change this and move it out of the config file
      - POSTGRES_PASSWORD=*EW>6,?3f3TLP2ikPdZs
      - SYNAPSE_ACME=1
      #- SYNAPSE_NO_TLS=1
    #volumes:
      # You may either store all the files in a local folder
      # - ./files:/data
      # .. or you may split this between different storage points
      # - ./files:/data
      # - /path/to/ssd:/data/uploads
      # - /path/to/large_hdd:/data/media
    depends_on:
      - db
      - bridge
    # In order to expose Synapse, remove one of the following, you might for
    # instance expose the TLS port directly:
    ports:
      - "8448:8448/tcp"
      # Devs should map 8008 locally for http testing
      #- "8008:8008/tcp"
      - "80:8009/tcp" # Necessary for automatic certificate requests
    # ... or use a reverse proxy, here is an example for traefik:
    #labels:
    #- traefik.enable=true
    #- traefik.frontend.rule=Host:my.matrix.Host
    #- traefik.port=8008

  db:
    image: docker.io/postgres:10-alpine
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=*EW>6,?3f3TLP2ikPdZs
    volumes:
      # You may store the database tables in a local folder..
      - ./schemas:/var/lib/postgresql/data
      # .. or store them on some high performance storage for better results
      # - /path/to/ssd/storage:/var/lib/postgresql/data

  irc:
    image: inspircd/inspircd-docker:latest
    ports:
      - "6667:6667/tcp"

  bridge:
    image: chatopia/matrix-appservice-irc:latest
    depends_on:
      - irc
    # We may not need this open to the host
    ports:
      - "9999:9999/tcp"
    entrypoint:
      - "/app/docker/start.sh"
      - "-c"
      - "config/server-config.yaml"
      - "-f"
      - "config/appservice-registration-irc.yaml"
      - "-p"
      - "9999"
